using AlphaBkBlzr.API.DataIntImplem.HumanResource;
using PayAPI.DataImplementation.DonBase;
using PayAPI.DataImplementation.TCl550Deplom;
using PayAPI.DataImplementation.TCl550MaritStatus;
using PayAPI.DataImplementation.TRH02Agent;
using PayAPI.DataImplementation.TSL02AgentRet;
using PayAPI.DataImplementation.TSL03Traitem;
using PayAPI.DataImplementation.TSL03TraitemAv;
using PayAPI.DataImplementation.TSL04ArchivINSS;
using PayAPI.DataImplementation.TSL04ArchivIPR;
using PayAPI.DataImplementation.TSL09ImputPay;
using PayAPI.DataIntImplem.AgDonIntialMoisRep;
using PayAPI.DataIntImplem.AgRegAugmBase;
using PayAPI.DataIntImplem.AgRetCotisation;
using PayAPI.DataIntImplem.CalculSalaire;
using PayAPI.DataIntImplem.CongCircRequest;
using PayAPI.DataIntImplem.CongeRequestsF;
using PayAPI.DataIntImplem.Contrat;
using PayAPI.DataIntImplem.ContratModif;
using PayAPI.DataIntImplem.ContratSusp;
using PayAPI.DataIntImplem.Depart;
using PayAPI.DataIntImplem.DonBase;
using PayAPI.DataIntImplem.Exercice;
using PayAPI.DataIntImplem.Faute;
using PayAPI.DataIntImplem.FauteTRH055;
using PayAPI.DataIntImplem.GetHRCounts;
using PayAPI.DataIntImplem.GetUserCounts;
using PayAPI.DataIntImplem.Localisation;
using PayAPI.DataIntImplem.Mutation;
using PayAPI.DataIntImplem.ParamDonBase.TSc551BranchAndSubBranch;
using PayAPI.DataIntImplem.ParamSec;
using PayAPI.DataIntImplem.Personnel_RIM2;
using PayAPI.DataIntImplem.PlanningConge;
using PayAPI.DataIntImplem.PostModif;
using PayAPI.DataIntImplem.Promotion;
using PayAPI.DataIntImplem.Qualification;
using PayAPI.DataIntImplem.Report;
using PayAPI.DataIntImplem.RubSalCompte;
using PayAPI.DataIntImplem.Salaire;
using PayAPI.DataIntImplem.SalProcess;
using PayAPI.DataIntImplem.TCl550Branch;
using PayAPI.DataIntImplem.TCl550Departement;
using PayAPI.DataIntImplem.TCl550DomEtud;
using PayAPI.DataIntImplem.TCl550Fonction;
using PayAPI.DataIntImplem.TCl550NatIDType;
using PayAPI.DataIntImplem.TCl550NivEtud;
using PayAPI.DataIntImplem.TCl550Sexe;
using PayAPI.DataIntImplem.TCl550Status;
using PayAPI.DataIntImplem.TCl550Universite;
using PayAPI.DataIntImplem.TCl550User;
using PayAPI.DataIntImplem.TSL02AgDimAugmSal;
using PayAPI.DataIntImplem.TSL02AgHSup;
using PayAPI.DataIntImplem.TSL02TracEvSal;
using PayAPI.DataIntImplem.TSL550TpDimAugSal;
using PayAPI.DataIntImplem.TxDAT;
using PayAPI.DataIntImplem.TypeCongCircons;
using PayAPI.DataIntImplem.TypeSalaire;
using PayAPI.RepServices;
using PayAPI.StringCon;
using PayLibrary.AgRegAugmBase;
using PayLibrary.CalculSalaire;
using PayLibrary.Cl550Branch;
using PayLibrary.CongCircRequest;
using PayLibrary.CongeRequestF;
using PayLibrary.Contrat;
using PayLibrary.ContratModif;
using PayLibrary.ContratSusp;
using PayLibrary.Depart;
using PayLibrary.DonIntialMois;
using PayLibrary.Exercice;
using PayLibrary.Faute;
using PayLibrary.FauteTRH055;
using PayLibrary.GetHRCounts;
using PayLibrary.GetUserCounts;
using PayLibrary.Gravite;
using PayLibrary.InterfParamSec;
using PayLibrary.InterfPrmDonBase;
using PayLibrary.IReport;
using PayLibrary.Localisation;
using PayLibrary.ParamDonBase.TSc551BranchAndSubBranch;
using PayLibrary.Permission;
using PayLibrary.Personnel_RIM2;
using PayLibrary.PlanningConge;
using PayLibrary.PostModif;
using PayLibrary.Promotion;
using PayLibrary.Qualification;
using PayLibrary.RubSalCompte;
using PayLibrary.Saction;
using PayLibrary.Salaire;
using PayLibrary.SalProcess;
using PayLibrary.TCl550Departement;
using PayLibrary.TCl550Deplom;
using PayLibrary.TCl550DomEtud;
using PayLibrary.TCl550Fonction;
using PayLibrary.TCl550MaritStatus;
using PayLibrary.TCl550NatIDType;
using PayLibrary.TCl550NivEtudId;
using PayLibrary.TCl550Sexe;
using PayLibrary.TCl550Status;
using PayLibrary.TCl550Universite;
using PayLibrary.TCl550User;
using PayLibrary.TCt550TpTransTout;
using PayLibrary.Training;
using PayLibrary.TrainingField;
using PayLibrary.TRH02Agent;
using PayLibrary.TRH550TypeSalaire;
using PayLibrary.TSL02AgDimAugmSal;
using PayLibrary.TSL02AgentRet;
using PayLibrary.TSL02AgHSup;
using PayLibrary.TSL02TracEvSal;
using PayLibrary.TSL03Traitem;
using PayLibrary.TSL03TraitemAv;
using PayLibrary.TSL04ArchivINSS;
using PayLibrary.TSL04ArchivIPR;
using PayLibrary.TSL09ImputPay;
using PayLibrary.TSL550TpDimAugSal;
using PayLibrary.TSL550TPHSup;
using PayLibrary.TxDAT;
using PayLibrary.TypeCongCircons;
using PayLibrary.TypeSaction;
using RimProjectAPi.DataIntImplem.DocVal;
using Scalar.AspNetCore;
using static PayAPI.RepServices.AgentComBranchService;
using static PayAPI.RepServices.AgentComListPrimeService;
using static PayAPI.RepServices.AgentComListPrimeVerifService;
using static PayAPI.RepServices.AgentComSubBranchService;
using static PayAPI.RepServices.SuperviseurZonervice;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
string connectionString = builder.Configuration.GetConnectionString("ApiConnection");
ClassConString.sConnectionString = connectionString;

builder.Services.AddScoped<ITRH02Agent, TRH02AgentImpl>();
builder.Services.AddScoped<ITSL02AgentRet, TSL02AgentRetImpl>();
builder.Services.AddScoped<ITSL03Traitem, TSL03TraitemImpl>();
builder.Services.AddScoped<ITSL03TraitemAv, TSL03TraitemAvImpl>();
builder.Services.AddScoped<ITSL04ArchivINSS, TSL04ArchivINSSImpl>();
builder.Services.AddScoped<ITSL04ArchivIPR, TSL04ArchivIPRImpl>();
builder.Services.AddScoped<ITSL09ImputPay, TSL09ImputPayImpl>();
builder.Services.AddScoped<ITCl550MaritStatus, TCl550MaritStatusImpl>();
builder.Services.AddScoped<ITCl550Deplom, TCl550DeplomImpl>();
builder.Services.AddScoped<ITCl550Branch, TCl550BranchImpl>();
builder.Services.AddScoped<ITCl550Departement, TCl550DepartementImpl>();
builder.Services.AddScoped<ITCl550Fonction, TCl550FonctionImpl>();
builder.Services.AddScoped<ITCl550NivEtudId, TCl550NivEtudIdImpl>();
builder.Services.AddScoped<ITCl550DomEtud, TCl550DomEtudImpl>();
builder.Services.AddScoped<ITCl550Universite, TCl550UniversiteImpl>();
builder.Services.AddScoped<ITCl550Status, TCl550StatusImpl>();
builder.Services.AddScoped<ITCl550User, TCl550UserImpl>();
builder.Services.AddScoped<ITCl550Sexe, TCl550SexeImpl>();
builder.Services.AddScoped<ITSL550TPHSup, TSL550TPHSupImpl>();
builder.Services.AddScoped<ITSL550TpDimAugSal, TSL550TpDimAugSalImpl>();
builder.Services.AddScoped<ITSL02TracEvSal, TSL02TracEvSalImpl>();
builder.Services.AddScoped<ITSL02AgHSup, TSL02AgHSupImpl>();
builder.Services.AddScoped<ITSL02AgRetPayment, TSL02AgRetAugmBaseImpl>();
builder.Services.AddScoped<ITSL02AgDimAugmSal, TSL02AgDimAugmSalImpl>();
builder.Services.AddScoped<IUserLogin, UserLoginImplement>();
builder.Services.AddScoped<ITSc551User, TSc551UserImpl>();
builder.Services.AddScoped<ITabPrmNivOne, TabPrmNivOneImplement>();
builder.Services.AddScoped<ITSc551SubMenu, TSc551SubMenuImplement>();
builder.Services.AddScoped<ITSL550Exercice, ExerciceImpl>();
builder.Services.AddScoped<ITSL00Process, SalProcessImpl>();
builder.Services.AddScoped<ITSL02AgRetCotis, TSL02AgRetCotisImpl>();
builder.Services.AddScoped<ITSL02AgRetPayment, TSL02AgRetAugmBaseImpl>();
builder.Services.AddScoped<ITSL02AgRegAugmMois, TSL02AgRegAugmMoisImpl>();
builder.Services.AddScoped<ITSL02AgRetPaymentMois, TSL02AgRetPaymentMoisImpl>();
builder.Services.AddScoped<ITSL02AgRetOccasMois, TSL02AgRetOccasMoisImpl>();
builder.Services.AddScoped<ITSL02AgRetCotisMois, TSL02AgRetCotisMoisImpl>();
builder.Services.AddScoped<ITVeh99Rapport, TVeh99RapportImpl>();
builder.Services.AddScoped<ITSl550RubSalCompte, TSl550RubSalCompteImpl>();
builder.Services.AddScoped<ITCl550NatIDType, TCl550NatIDTypeImplm>();
builder.Services.AddScoped<IClasContrat, ContratImpl>();
builder.Services.AddScoped<IPersonnel_RIM2, Personnel_RIM2Implm>();
builder.Services.AddScoped<IQualification, QualificationImplm>();
builder.Services.AddScoped<IDepart, DepartImplm>();
builder.Services.AddScoped<IReportingService, ReportingService>();
builder.Services.AddScoped<IListPayGenService, ClasListPayGenService>();
builder.Services.AddScoped<IListRetenueService, ClasListRetNStatService>();
builder.Services.AddScoped<IAgentComListPrimeService, ClasListPrimeGenService>();
builder.Services.AddScoped<ITSc551SubBranch, TSc551SubBranchImpl>();
builder.Services.AddScoped<IAgentComListBranchService, ClasListBranchService>();
builder.Services.AddScoped<IAgentComListSubBranchService, ClasListSubBranchService>();
builder.Services.AddScoped<IAgentComListPrimeVerifService, ClasListPrimeGenVerifService>();
builder.Services.AddScoped<ISuperviseurZoneService, ClasSuperviseurZoneService>();
builder.Services.AddScoped<IPrimeListByBranchPay, PrimeListPayByBranchService>();
builder.Services.AddScoped<IPayrollListRIPPSService, PayrollListRIPPSService>();
builder.Services.AddScoped<IListPayByBranchService, ClasListPayByBranchService>();
builder.Services.AddScoped<IRetCaisseSolidService, RetCaisseSolidService>();
builder.Services.AddScoped<IRetBourseService, RetBourseService>();
builder.Services.AddScoped<IRetCaisseEpargneService, RetCaisseEpargneService>();
builder.Services.AddScoped<IRetCaisseSolidService, RetCaisseSolidService>();
builder.Services.AddScoped<IRetEjohezaService, RetEjohezaService>();
builder.Services.AddScoped<IRetPrimeLifeService, RetPrimeLifeService>();
builder.Services.AddScoped<IRetSanLamSercice, RetSanLamSercice>();
builder.Services.AddScoped<ICalculerSalaire, CalculSalaireImpl>();
builder.Services.AddScoped<ITHRPlanningConge, ITHRPlanningCongeImpl>();
builder.Services.AddScoped<ITHRCongCircRequest, THRCongCircRequestImpl>();
builder.Services.AddScoped<ITHRCongCircRequestNew, THRCongCircRequestNewImpl>();
// en
builder.Services.AddScoped<ITRH05Mutation, TRH05MutationImpl>();
builder.Services.AddScoped<ITRH05Localisation, TRH05LocalisationImpl>();
builder.Services.AddScoped<ITHR05ContratModif, THR05ContratModifImpl>();
builder.Services.AddScoped<ITRH05PostModif, TRH05PostModifImpl>();
builder.Services.AddScoped<ITRH05Promotion, TRH05PromotionImpl>();
builder.Services.AddScoped<ITSL02Salaire, ITSL02SalaireImpl>();
builder.Services.AddScoped<ITRH550TypeSalaire, TRH550TypeSalaireImpl>();
builder.Services.AddScoped<IClassGetHRCounts, ClassGetHRCountsImpl>();
builder.Services.AddScoped<IClassGetAgentCounts, ClassGetUserCountsImpl>();
builder.Services.AddScoped<ITRH03ContratSusp, TRH03ContratSuspImpl>();
builder.Services.AddScoped<ITRH051TypeCongCircons, TRH051TypeCongCirconsImpl>();
builder.Services.AddScoped<ITRH03Training, TRH03TrainingImpl>();
builder.Services.AddScoped<ITRH05Saction, TRH05SactionImp>();
builder.Services.AddScoped<ITRH031TrainingField, TRH031TrainingFieldImpl>();
builder.Services.AddScoped<ITRH051TypeSaction, TRH051TypeSactionImpl>();
builder.Services.AddScoped<ITRH042Gravite, TRH042GraviteImpl>();
builder.Services.AddScoped<ITRH04FAUTE, TRH04FAUTEImpl>();
builder.Services.AddScoped<ITRH055FAUTE, TRH055FAUTEImpl>();
builder.Services.AddScoped<ITRH05Permission, TRH05PermissionImpl>();
builder.Services.AddScoped<ITCt550TpTransTout, TCt550TpTransToutImpl>();
builder.Services.AddScoped<ITCpt050TxDAT, TCpt050TxDATImpl>();

builder.Services.AddScoped<ITSc551SubBranchDir, TSc551SubBranchDirImpl>();
builder.Services.AddScoped<ITSc551BranchDir, TSc551BranchDirImpl>();


builder.Services.AddControllers();
// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
   app.MapOpenApi();
   app.MapScalarApiReference();

}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
